# Generated by Django 5.2.16 on 2026-07-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0003_collectionrun_failed_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField()),
                ('source_type', models.CharField(choices=[('official', '官方')], max_length=20)),
                ('collection_method', models.CharField(choices=[('rss', 'RSS / Atom'), ('web', '公开结构化列表')], max_length=20)),
                ('observation_scope', models.CharField(choices=[('eth_direct', 'ETH 直接事实'), ('crypto_systemic', '加密市场系统性')], max_length=30)),
                ('base_url', models.URLField(max_length=500)),
                ('feed_url', models.URLField(blank=True, max_length=500)),
                ('parser_version', models.CharField(max_length=80)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('trusted_coverage_end', models.DateTimeField(blank=True, null=True)),
                ('last_inspection_status', models.CharField(choices=[('never_run', '从未运行'), ('passed', '通过'), ('warning', '警告'), ('failed', '失败')], default='never_run', max_length=20)),
                ('health_status', models.CharField(choices=[('never_run', '从未运行'), ('healthy', '健康'), ('degraded', '降级'), ('broken', '故障')], default='never_run', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NewsRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.CharField(blank=True, max_length=255)),
                ('original_url', models.URLField(blank=True, max_length=1000)),
                ('canonical_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('updated_at_source', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('source_category', models.CharField(blank=True, max_length=255)),
                ('source_tags', models.JSONField(default=list)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('identity_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_seen_news_records', to='collection.collectionrun')),
                ('last_collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_news_records', to='collection.collectionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='news_data.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='news_src_pub_desc_idx'), models.Index(fields=['identity_hash'], name='news_identity_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_item_id', ''), _negated=True), fields=('source', 'source_item_id'), name='news_source_item_unique'), models.UniqueConstraint(condition=models.Q(('canonical_url', ''), _negated=True), fields=('source', 'canonical_url'), name='news_source_url_unique'), models.UniqueConstraint(fields=('source', 'identity_hash'), name='news_source_identity_unique')],
            },
        ),
        migrations.CreateModel(
            name='NewsCollectionDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('feed', 'Feed'), ('page', '分页')], max_length=20)),
                ('unit_identifier', models.CharField(max_length=255)),
                ('request_started_at', models.DateTimeField()),
                ('request_finished_at', models.DateTimeField()),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=1000)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('response_size', models.PositiveIntegerField(default=0)),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.CharField(max_length=80)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('parsed_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('earliest_published_at', models.DateTimeField(blank=True, null=True)),
                ('latest_published_at', models.DateTimeField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('reached_time_boundary', '到达时间边界'), ('no_next_page', '没有下一页'), ('source_history_limited', '来源历史有限'), ('safety_page_limit', '安全页数上限'), ('pagination_loop', '分页循环'), ('request_failed', '请求失败'), ('completed', '完成')], max_length=40)),
                ('coverage_complete', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_diagnostics', to='collection.collectionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics', to='news_data.newssource')),
            ],
            options={
                'ordering': ['-request_started_at', '-id'],
                'indexes': [models.Index(fields=['source', '-request_started_at'], name='news_diag_src_req_idx')],
            },
        ),
    ]
