# Generated by Django 5.2.16 on 2026-08-27 15:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemeMarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="geckoterminal", max_length=40)),
                ("chain", models.CharField(max_length=32)),
                ("dex", models.CharField(max_length=80)),
                ("token_address", models.CharField(max_length=128)),
                ("pair_address", models.CharField(max_length=128)),
                ("symbol", models.CharField(blank=True, max_length=80)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("pair_created_at", models.DateTimeField()),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=24, max_digits=50, null=True
                    ),
                ),
                (
                    "liquidity_usd",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                (
                    "fdv",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                (
                    "volume_5m",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                (
                    "volume_1h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                ("buys_5m", models.PositiveIntegerField(blank=True, null=True)),
                ("sells_5m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price_change_5m",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                (
                    "price_change_1h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp", "pair_address"],
                "indexes": [
                    models.Index(
                        fields=["chain", "pair_address", "-timestamp"],
                        name="meme_snapshot_pair_time_idx",
                    ),
                    models.Index(
                        fields=["chain", "-pair_created_at"],
                        name="meme_snapshot_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "chain", "pair_address", "timestamp"),
                        name="meme_snapshot_source_pair_time_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemeAnomalyEventRecord",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(default="market_spike", max_length=80),
                ),
                ("event_time", models.DateTimeField()),
                ("chain", models.CharField(max_length=32)),
                ("token_address", models.CharField(max_length=128)),
                ("pair_address", models.CharField(max_length=128)),
                ("symbol", models.CharField(blank=True, max_length=80)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("pair_age_minutes", models.PositiveIntegerField()),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=24, max_digits=50, null=True
                    ),
                ),
                (
                    "price_change_5m",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                (
                    "price_change_1h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_5m",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                (
                    "liquidity_usd",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=50, null=True
                    ),
                ),
                ("buys_5m", models.PositiveIntegerField(blank=True, null=True)),
                ("sells_5m", models.PositiveIntegerField(blank=True, null=True)),
                ("triggered_rules", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_events",
                        to="meme_monitor.mememarketsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "chain",
                            "token_address",
                            "anomaly_type",
                            "-event_time",
                        ],
                        name="meme_event_cooldown_idx",
                    ),
                    models.Index(fields=["-event_time"], name="meme_event_time_idx"),
                ],
            },
        ),
    ]
