# Generated by Django 5.2.16 on 2026-08-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meme_monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemeMonitorRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="geckoterminal", max_length=40)),
                ("chain", models.CharField(max_length=32)),
                (
                    "mode",
                    models.CharField(
                        choices=[("continuous", "常驻监听"), ("once", "单轮执行")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("stopped", "已停止"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("process_id", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField()),
                ("cycle_count", models.PositiveIntegerField(default=0)),
                ("successful_cycle_count", models.PositiveIntegerField(default=0)),
                ("failed_cycle_count", models.PositiveIntegerField(default=0)),
                ("latest_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["chain", "-started_at"], name="meme_run_chain_start_idx"
                    ),
                    models.Index(
                        fields=["status", "-heartbeat_at"],
                        name="meme_run_status_beat_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MemeMonitorCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_pairs", models.PositiveIntegerField(default=0)),
                ("tracked_pairs", models.PositiveIntegerField(default=0)),
                ("saved_snapshots", models.PositiveIntegerField(default=0)),
                ("detected_anomalies", models.PositiveIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="meme_monitor.mememonitorrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["run", "-started_at"], name="meme_cycle_run_start_idx"
                    ),
                    models.Index(
                        fields=["status", "-started_at"], name="meme_cycle_status_idx"
                    ),
                ],
            },
        ),
    ]
