# Generated by Django 5.2.16 on 2026-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meme_monitor", "0002_mememonitorrun_mememonitorcycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mememonitorcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "执行中"),
                    ("succeeded", "成功"),
                    ("partial", "部分成功"),
                    ("failed", "失败"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
