# Generated by Django 5.2.16 on 2026-08-31 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_monitor', '0004_add_monitor_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeLaunchpadTokenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='geckoterminal', max_length=40)),
                ('chain', models.CharField(max_length=32)),
                ('token_address', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('launchpad_pair_address', models.CharField(max_length=128)),
                ('current_pair_address', models.CharField(max_length=128)),
                ('migrated_destination_pair_address', models.CharField(blank=True, max_length=128)),
                ('graduation_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-observed_at', 'token_address'],
                'indexes': [models.Index(fields=['chain', '-observed_at'], name='meme_launchpad_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'chain', 'token_address'), name='meme_launchpad_token_unique')],
            },
        ),
        migrations.CreateModel(
            name='MemeContinuationResearchEpisode',
            fields=[
                ('episode_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='geckoterminal', max_length=40)),
                ('chain', models.CharField(max_length=32)),
                ('token_address', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('rule_version', models.CharField(default='launchpad_5m_v1', max_length=40)),
                ('status', models.CharField(choices=[('waiting_entry', '等待可执行入场'), ('waiting_exit', '跟踪 5 分钟'), ('completed', '研究完成'), ('unavailable', '无法形成样本')], default='waiting_entry', max_length=24)),
                ('failure_reason', models.CharField(blank=True, max_length=120)),
                ('triggered_at', models.DateTimeField()),
                ('launchpad_pair_address', models.CharField(max_length=128)),
                ('trigger_pair_address', models.CharField(max_length=128)),
                ('current_pair_address', models.CharField(max_length=128)),
                ('migrated_destination_pair_address', models.CharField(blank=True, max_length=128)),
                ('migration_detected_at', models.DateTimeField(blank=True, null=True)),
                ('entry_target_at', models.DateTimeField()),
                ('entry_observed_at', models.DateTimeField(blank=True, null=True)),
                ('entry_pair_address', models.CharField(blank=True, max_length=128)),
                ('entry_price_usd', models.DecimalField(blank=True, decimal_places=24, max_digits=50, null=True)),
                ('entry_liquidity_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('entry_price_impact_pct', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_target_at', models.DateTimeField(blank=True, null=True)),
                ('exit_observed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_pair_address', models.CharField(blank=True, max_length=128)),
                ('exit_price_usd', models.DecimalField(blank=True, decimal_places=24, max_digits=50, null=True)),
                ('exit_liquidity_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('exit_price_impact_pct', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('notional_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_bps_per_side', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gross_return_pct', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('net_return_pct', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('cost_model', models.CharField(default='constant_product_v1_no_token_tax', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='continuation_episode', to='meme_monitor.memeanomalyeventrecord')),
            ],
            options={
                'ordering': ['-triggered_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'entry_target_at'], name='meme_research_entry_idx'), models.Index(fields=['status', 'exit_target_at'], name='meme_research_exit_idx'), models.Index(fields=['chain', 'token_address'], name='meme_research_token_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'chain', 'token_address', 'rule_version'), name='meme_research_first_token_unique')],
            },
        ),
    ]
