# Generated by Django 5.2.16 on 2026-08-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_monitor', '0005_memelaunchpadtokenstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeanomalyeventrecord',
            name='source',
            field=models.CharField(default='geckoterminal', max_length=40),
        ),
        migrations.AlterField(
            model_name='memeanomalyeventrecord',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='meme_monitor.mememarketsnapshot'),
        ),
        migrations.CreateModel(
            name='MemePairState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='geckoterminal', max_length=40)),
                ('chain', models.CharField(max_length=32)),
                ('dex', models.CharField(max_length=80)),
                ('token_address', models.CharField(max_length=128)),
                ('pair_address', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('pair_created_at', models.DateTimeField()),
                ('price_usd', models.DecimalField(blank=True, decimal_places=24, max_digits=50, null=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('fdv', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('volume_5m', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('volume_1h', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('buys_5m', models.PositiveIntegerField(blank=True, null=True)),
                ('sells_5m', models.PositiveIntegerField(blank=True, null=True)),
                ('price_change_5m', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('price_change_1h', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('volume_5m_history', models.JSONField(default=list)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-observed_at', 'pair_address'],
                'indexes': [models.Index(fields=['chain', '-pair_created_at'], name='meme_state_created_idx'), models.Index(fields=['chain', '-observed_at'], name='meme_state_observed_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'chain', 'pair_address'), name='meme_pair_state_source_pair_unique')],
            },
        ),
    ]
