# Generated by Django 5.2.16 on 2026-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookFiveMinuteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('mid_open', models.DecimalField(decimal_places=18, max_digits=40)),
                ('mid_high', models.DecimalField(decimal_places=18, max_digits=40)),
                ('mid_low', models.DecimalField(decimal_places=18, max_digits=40)),
                ('mid_close', models.DecimalField(decimal_places=18, max_digits=40)),
                ('spread_bps_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('spread_bps_max', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('spread_bps_end', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_depth_top5_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top5_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('bid_depth_top10_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top10_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('bid_depth_top20_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top20_quote_mean', models.DecimalField(decimal_places=18, max_digits=40)),
                ('imbalance_top5_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top5_end', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top10_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top10_end', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top20_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top20_end', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('snapshot_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['interval_start'],
                'indexes': [models.Index(fields=['symbol', '-interval_start'], name='orderbook_5m_symbol_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'interval_start'), name='unique_orderbook_5m_summary')],
            },
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('sampled_at', models.DateTimeField()),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('update_id', models.PositiveBigIntegerField()),
                ('best_bid', models.DecimalField(decimal_places=18, max_digits=40)),
                ('best_ask', models.DecimalField(decimal_places=18, max_digits=40)),
                ('mid_price', models.DecimalField(decimal_places=18, max_digits=40)),
                ('spread', models.DecimalField(decimal_places=18, max_digits=40)),
                ('spread_bps', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_depth_top5_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top5_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('bid_depth_top10_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top10_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('bid_depth_top20_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('ask_depth_top20_quote', models.DecimalField(decimal_places=18, max_digits=40)),
                ('imbalance_top5', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top10', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('imbalance_top20', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sampled_at'],
                'indexes': [models.Index(fields=['symbol', '-sampled_at'], name='orderbook_symbol_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'sampled_at'), name='unique_orderbook_snapshot_time')],
            },
        ),
    ]
