# Generated by Django 5.2.16 on 2026-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microstructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrostructureCollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('starting', '启动中'), ('running', '运行中'), ('stopping', '停止中'), ('stopped', '已停止'), ('failed', '异常')], default='starting', max_length=20)),
                ('connection_state', models.CharField(choices=[('connecting', '连接中'), ('connected', '已连接'), ('reconnecting', '重连中'), ('disconnected', '未连接')], default='connecting', max_length=20)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('received_messages', models.PositiveBigIntegerField(default=0)),
                ('saved_snapshots', models.PositiveBigIntegerField(default=0)),
                ('reconnect_count', models.PositiveIntegerField(default=0)),
                ('latest_event_time', models.DateTimeField(blank=True, null=True)),
                ('latest_sampled_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='micro_run_created_idx'), models.Index(fields=['status'], name='micro_run_status_idx')],
            },
        ),
    ]
