# Generated by Django 5.2.16 on 2026-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microstructure', '0003_collector_latest_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('minute_start', models.DateTimeField()),
                ('minute_end', models.DateTimeField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('quote_volume', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('taker_buy_quote', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('taker_sell_quote', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('delta_quote', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('first_trade_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_trade_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kline_closed', models.BooleanField(default=False)),
                ('bid_depth_open', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_depth_close', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_depth_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_depth_sum', models.DecimalField(decimal_places=18, default=0, max_digits=50)),
                ('ask_depth_open', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('ask_depth_close', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('ask_depth_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('ask_depth_sum', models.DecimalField(decimal_places=18, default=0, max_digits=50)),
                ('spread_bps_mean', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('spread_bps_p95', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('spread_bps_sum', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('spread_bps_samples', models.JSONField(blank=True, default=list)),
                ('book_sample_count', models.PositiveSmallIntegerField(default=0)),
                ('coverage_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('first_book_sample_at', models.DateTimeField(blank=True, null=True)),
                ('last_book_sample_at', models.DateTimeField(blank=True, null=True)),
                ('latest_event_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['minute_start'],
            },
        ),
        migrations.DeleteModel(
            name='OrderBookFiveMinuteSummary',
        ),
        migrations.DeleteModel(
            name='OrderBookSnapshot',
        ),
        migrations.RemoveField(
            model_name='microstructurecollectorrun',
            name='saved_snapshots',
        ),
        migrations.AddField(
            model_name='microstructurecollectorrun',
            name='saved_minute_updates',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='marketminute',
            index=models.Index(fields=['symbol', '-minute_start'], name='market_minute_symbol_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketminute',
            constraint=models.UniqueConstraint(fields=('symbol', 'minute_start'), name='unique_market_minute'),
        ),
    ]
