# Generated by Django 5.2.16 on 2026-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microstructure', '0004_marketminute_delete_orderbookfiveminutesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microstructurecollectorrun',
            name='oi_process_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
