# Generated by Django 5.2.16 on 2026-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microstructure', '0009_live_market_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpilotreport',
            name='selection_reason',
            field=models.CharField(choices=[('absolute_return_ge_2pct', '候选异动'), ('absolute_return_threshold', '阈值异动'), ('calm_control', '平静对照')], max_length=40),
        ),
    ]
