# Generated by Django 5.2.16 on 2026-08-31 12:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microstructure', '0010_generic_live_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrostructureResearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('data_cutoff', models.DateTimeField()),
                ('calculation_version', models.CharField(max_length=80)),
                ('minute_count', models.PositiveIntegerField(default=0)),
                ('labeled_count', models.PositiveIntegerField(default=0)),
                ('labels_updated', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['symbol', '-generated_at'], name='micro_research_snap_idx')],
            },
        ),
    ]
