# Generated by Django 5.2.16 on 2026-08-05 10:38

import apps.market_funds.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0008_alter_collectionrun_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('public_label', models.CharField(blank=True, max_length=300)),
                ('address_type', models.CharField(choices=[('unknown', '未知'), ('eoa', 'EOA'), ('contract', '合约')], default='unknown', max_length=20)),
                ('label_source', models.CharField(blank=True, max_length=40)),
                ('label_is_public', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='SourceDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40, unique=True)),
                ('source_url', models.URLField(max_length=300)),
                ('response_sha256', models.CharField(blank=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('policy_status', models.CharField(default='allowed', max_length=30)),
                ('policy_note', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtfFlowDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True)),
                ('ticker', models.CharField(max_length=20)),
                ('flow_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=80)),
                ('is_total', models.BooleanField(default=False)),
                ('source', models.CharField(default='Farside', max_length=40)),
                ('source_url', models.URLField(max_length=300)),
                ('retrieved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trade_date', 'is_total', 'ticker'],
                'indexes': [models.Index(fields=['ticker', '-trade_date'], name='fund_etf_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('trade_date', 'ticker'), name='fund_etf_day_ticker_unique')],
            },
        ),
        migrations.CreateModel(
            name='StablecoinSupplyDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(db_index=True)),
                ('chain', models.CharField(default='Ethereum', max_length=32)),
                ('stablecoin_symbol', models.CharField(blank=True, default='', max_length=20)),
                ('circulating_supply', models.DecimalField(decimal_places=8, max_digits=40)),
                ('circulating_supply_usd', models.DecimalField(decimal_places=8, max_digits=40)),
                ('minted_supply_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('bridged_supply_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('source', models.CharField(default='DeFiLlama', max_length=40)),
                ('source_url', models.URLField(max_length=300)),
                ('retrieved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-observation_date', 'stablecoin_symbol'],
                'indexes': [models.Index(fields=['chain', 'stablecoin_symbol', '-observation_date'], name='fund_stablecoin_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('observation_date', 'chain', 'stablecoin_symbol'), name='fund_stablecoin_day_chain_symbol_unique')],
            },
        ),
        migrations.CreateModel(
            name='AddressBalanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('balance_eth', models.DecimalField(decimal_places=18, max_digits=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='Etherscan', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances', to='market_funds.addressentity')),
            ],
            options={
                'ordering': ['-snapshot_date', 'rank'],
                'indexes': [models.Index(fields=['address', '-snapshot_date'], name='fund_address_history_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'address'), name='fund_address_snapshot_unique'), models.UniqueConstraint(fields=('snapshot_date', 'rank'), name='fund_address_rank_unique')],
            },
        ),
        migrations.CreateModel(
            name='FundDataInspectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('stablecoin', '稳定币供应'), ('etf', 'ETF 每日资金流'), ('addresses', '公开地址余额')], max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', '待判定'), ('passed', '通过'), ('issues', '发现问题'), ('blocked', '来源策略阻止')], default='pending', max_length=20)),
                ('actual_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=apps.market_funds.models.empty_quality_details)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_inspection_runs', to='collection.collectionrun')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', '-started_at'], name='fund_quality_task_idx')],
            },
        ),
    ]
