# Generated by Django 5.2.16 on 2026-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance')], max_length=20)),
                ('market_type', models.CharField(choices=[('usd_m_futures', 'USD-M Futures')], max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(choices=[('1d', '1d'), ('1h', '1h')], max_length=5)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=18, max_digits=40)),
                ('high', models.DecimalField(decimal_places=18, max_digits=40)),
                ('low', models.DecimalField(decimal_places=18, max_digits=40)),
                ('close', models.DecimalField(decimal_places=18, max_digits=40)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=40)),
                ('quote_volume', models.DecimalField(decimal_places=18, max_digits=40)),
                ('trade_count', models.PositiveBigIntegerField()),
                ('taker_buy_base_volume', models.DecimalField(decimal_places=18, max_digits=40)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=18, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['open_time'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='kline_sym_int_open_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market_type', 'symbol', 'interval', 'open_time'), name='unique_kline_market_open_time')],
            },
        ),
    ]
