# Generated by Django 5.2.16 on 2026-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance')], max_length=20)),
                ('market_type', models.CharField(choices=[('usd_m_futures', 'USD-M Futures')], max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('funding_time', models.DateTimeField()),
                ('funding_rate', models.DecimalField(decimal_places=18, max_digits=40)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('rate_type', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['funding_time'],
                'indexes': [models.Index(fields=['symbol', 'funding_time'], name='funding_sym_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market_type', 'symbol', 'funding_time'), name='unique_funding_market_time')],
            },
        ),
        migrations.CreateModel(
            name='OpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance')], max_length=20)),
                ('market_type', models.CharField(choices=[('usd_m_futures', 'USD-M Futures')], max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('period', models.CharField(choices=[('1h', '1h')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('sum_open_interest', models.DecimalField(decimal_places=18, max_digits=40)),
                ('sum_open_interest_value', models.DecimalField(decimal_places=18, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['symbol', 'period', 'timestamp'], name='oi_sym_period_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market_type', 'symbol', 'period', 'timestamp'), name='unique_oi_market_period_time')],
            },
        ),
    ]
