# Generated by Django 5.2.16 on 2026-08-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_alter_kline_interval_alter_openinterest_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeribitOptionInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.PositiveBigIntegerField(unique=True)),
                ('instrument_name', models.CharField(max_length=80, unique=True)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('settlement_currency', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=10)),
                ('strike', models.DecimalField(decimal_places=18, max_digits=40)),
                ('expiration_time', models.DateTimeField()),
                ('creation_time', models.DateTimeField()),
                ('contract_size', models.DecimalField(decimal_places=18, max_digits=40)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiration_time', 'strike', 'option_type'],
                'indexes': [models.Index(fields=['base_currency', 'is_active', 'expiration_time'], name='deribit_opt_active_exp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('strike__gt', 0)), name='deribit_option_strike_positive'), models.CheckConstraint(condition=models.Q(('contract_size__gt', 0)), name='deribit_contract_size_positive')],
            },
        ),
        migrations.CreateModel(
            name='DeribitVolatilityIndexCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ETH', 'ETH')], max_length=10)),
                ('resolution', models.CharField(choices=[('1h', '1h')], max_length=5)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=18, max_digits=40)),
                ('high', models.DecimalField(decimal_places=18, max_digits=40)),
                ('low', models.DecimalField(decimal_places=18, max_digits=40)),
                ('close', models.DecimalField(decimal_places=18, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['open_time'],
                'indexes': [models.Index(fields=['currency', 'resolution', 'open_time'], name='dvol_curr_res_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'resolution', 'open_time'), name='unique_deribit_dvol_candle'), models.CheckConstraint(condition=models.Q(('high__gte', models.F('low'))), name='deribit_dvol_high_gte_low')],
            },
        ),
        migrations.CreateModel(
            name='DeribitOptionMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('source_timestamp', models.DateTimeField()),
                ('underlying_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('mark_iv', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('mid_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('volume_usd_24h', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_snapshots', to='market_data.deribitoptioninstrument')),
            ],
            options={
                'ordering': ['observed_at', 'instrument__expiration_time', 'instrument__strike'],
                'indexes': [models.Index(fields=['observed_at'], name='deribit_opt_obs_idx'), models.Index(fields=['instrument', '-observed_at'], name='deribit_opt_inst_obs_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'observed_at'), name='unique_deribit_option_snapshot'), models.CheckConstraint(condition=models.Q(('open_interest__isnull', True), ('open_interest__gte', 0), _connector='OR'), name='deribit_option_oi_nonnegative'), models.CheckConstraint(condition=models.Q(('mark_iv__isnull', True), ('mark_iv__gte', 0), _connector='OR'), name='deribit_option_iv_nonnegative')],
            },
        ),
    ]
