# Generated by Django 5.2.16 on 2026-08-01 09:09

from datetime import UTC, datetime, time, timedelta
from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


NEWS_WORKFLOW_SCHEDULE_NAME = "新闻每日采集、质量检查与增量分析"


def create_news_workflow_schedule(apps, schema_editor):
    NewsWorkflowSchedule = apps.get_model("scheduling", "NewsWorkflowSchedule")
    run_time = time(8, 35)
    zone = ZoneInfo("Asia/Shanghai")
    now = timezone.now().astimezone(zone)
    candidate = datetime.combine(now.date(), run_time, tzinfo=zone)
    if candidate <= now:
        candidate += timedelta(days=1)
    NewsWorkflowSchedule.objects.get_or_create(
        name=NEWS_WORKFLOW_SCHEDULE_NAME,
        defaults={
            "enabled": False,
            "run_time": run_time,
            "timezone": "Asia/Shanghai",
            "next_run_at": candidate.astimezone(UTC),
        },
    )


def remove_news_workflow_schedule(apps, schema_editor):
    NewsWorkflowSchedule = apps.get_model("scheduling", "NewsWorkflowSchedule")
    NewsWorkflowSchedule.objects.filter(name=NEWS_WORKFLOW_SCHEDULE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collectionrun_news_source_and_more'),
        ('inspection', '0005_newsinspectionrun_source_and_more'),
        ('news_analysis', '0002_alter_newsanalysisrun_status_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('run_time', models.TimeField(default=time(8, 35))),
                ('timezone', models.CharField(default='Asia/Shanghai', editable=False, max_length=64)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            create_news_workflow_schedule,
            remove_news_workflow_schedule,
        ),
        migrations.CreateModel(
            name='NewsWorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', '定时'), ('manual', '手工')], max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=20)),
                ('ethereum_collection_status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20)),
                ('binance_collection_status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20)),
                ('ethereum_quality_status', models.CharField(choices=[('pending', '待检查'), ('passed', '通过'), ('warning', '警告'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20)),
                ('binance_quality_status', models.CharField(choices=[('pending', '待检查'), ('passed', '通过'), ('warning', '警告'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20)),
                ('analysis_status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('quality_issue_count', models.PositiveIntegerField(default=0)),
                ('analysis_candidate_count', models.PositiveIntegerField(default=0)),
                ('analysis_success_count', models.PositiveIntegerField(default=0)),
                ('analysis_failure_count', models.PositiveIntegerField(default=0)),
                ('analysis_skipped_count', models.PositiveIntegerField(default=0)),
                ('safe_error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_workflows', to='news_analysis.newsanalysisrun')),
                ('binance_collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='binance_news_workflows', to='collection.collectionrun')),
                ('binance_inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='binance_news_workflows', to='inspection.newsinspectionrun')),
                ('ethereum_collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ethereum_news_workflows', to='collection.collectionrun')),
                ('ethereum_inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ethereum_news_workflows', to='inspection.newsinspectionrun')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='scheduling.newsworkflowschedule')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['-started_at'], name='news_workflow_start_idx'), models.Index(fields=['schedule', '-started_at'], name='news_workflow_sched_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='news_workflow_one_running')],
            },
        ),
    ]
