# Generated by Django 5.2.16 on 2026-08-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0008_eventmergerun_canonicalevent_eventpairdecision_and_more'),
        ('scheduling', '0005_split_news_workflow_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsworkflowrun',
            name='event_merge_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_workflows', to='news_analysis.eventmergerun'),
        ),
        migrations.AddField(
            model_name='newsworkflowrun',
            name='event_merge_status',
            field=models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='newsworkflowrun',
            name='objective_fact_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsworkflowrun',
            name='objective_fact_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_workflows', to='news_analysis.objectivefactextractionrun'),
        ),
        migrations.AddField(
            model_name='newsworkflowrun',
            name='objective_fact_status',
            field=models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='newsworkflowrun',
            name='objective_fact_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
