# Generated by Django 5.2.16 on 2026-08-05 03:52

import apps.scheduling.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_newsworkflowrun_event_merge_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeribitOptionsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('dvol_lookback_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeribitOptionsWorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', '定时'), ('manual', '手工')], max_length=20)),
                ('observed_at', models.DateTimeField()),
                ('dvol_lookback_days', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分完成'), ('failed', '失败')], default='running', max_length=20)),
                ('details', models.JSONField(default=apps.scheduling.models.empty_deribit_options_details)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='scheduling.deribitoptionsschedule')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='deribit_workflow_start_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='deribit_options_one_running')],
            },
        ),
    ]
