# Generated by Django 5.2.16 on 2026-08-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_collectionrun_data_type'),
        ('market_funds', '0001_initial'),
        ('scheduling', '0010_rename_news_source_proxy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDataSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('task_type', models.CharField(choices=[('stablecoin', '稳定币供应'), ('etf', 'ETF 每日资金流'), ('addresses', '公开地址余额快照')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('run_time', models.TimeField()),
                ('supplement_run_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', editable=False, max_length=64)),
                ('lookback_days', models.PositiveSmallIntegerField(default=7)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['run_time', 'task_type'],
            },
        ),
        migrations.CreateModel(
            name='FundDataWorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('stablecoin', '稳定币供应'), ('etf', 'ETF 每日资金流'), ('addresses', '公开地址余额快照')], max_length=20)),
                ('trigger', models.CharField(choices=[('scheduled', '定时'), ('manual', '手工')], max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分完成'), ('failed', '失败')], default='running', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', '待判定'), ('passed', '通过'), ('issues', '发现问题'), ('blocked', '来源策略阻止')], default='pending', max_length=20)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_workflow_runs', to='collection.collectionrun')),
                ('inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='market_funds.funddatainspectionrun')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='scheduling.funddataschedule')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', '-started_at'], name='fund_workflow_task_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('task_type',), name='fund_workflow_one_running_per_task')],
            },
        ),
    ]
