# Generated by Django 5.2.16 on 2026-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_market_pilot_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpilotschedule',
            name='include_contextual_evidence',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='marketpilotschedule',
            name='outcome_horizons',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='marketpilotschedule',
            name='symbol',
            field=models.CharField(default='ETHUSDT', max_length=20),
        ),
        migrations.AddField(
            model_name='marketpilotschedule',
            name='window_hours',
            field=models.PositiveSmallIntegerField(default=4, editable=False),
        ),
    ]
