# Generated by Django 5.2.16 on 2026-08-31 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_zec_market_pilot_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSnapshotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('run_time', models.TimeField(default=datetime.time(0, 30))),
                ('timezone', models.CharField(default='Asia/Shanghai', editable=False, max_length=64)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
