# Generated by Django 5.2.16 on 2026-09-03 14:05

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新的开仓分析', max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('horizon_minutes', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('cutoff', models.DateTimeField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.JSONField(default=dict)),
                ('rows', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('calculation_version', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('question', models.TextField()),
                ('horizon_minutes', models.PositiveSmallIntegerField(default=60)),
                ('refresh_data', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', '等待分析'), ('running', '分析中'), ('succeeded', '已完成'), ('failed', '未完成')], default='queued', max_length=20)),
                ('progress', models.CharField(default='等待后台分析进程领取', max_length=180)),
                ('report', models.JSONField(default=dict)),
                ('safe_error', models.CharField(blank=True, max_length=300)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('prompt_text', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('usage', models.JSONField(default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='trading_assistant.conversation')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading_assistant.marketsnapshot')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=80)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='trading_assistant.analysisturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisturn',
            index=models.Index(fields=['status', 'created_at'], name='assistant_turn_queue'),
        ),
        migrations.AddConstraint(
            model_name='analysisturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'request_id'), name='assistant_request_once'),
        ),
        migrations.AddConstraint(
            model_name='analysisturn',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('conversation',), name='assistant_one_active_turn'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.UniqueConstraint(fields=('turn', 'cache_key'), name='assistant_tool_once'),
        ),
    ]
