# Generated by Django 5.2.16 on 2026-09-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisturn',
            name='input_context',
            field=models.JSONField(default=dict),
        ),
    ]
