# Generated by Django 5.2.16 on 2026-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_assistant', '0002_analysisturn_input_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisturn',
            name='horizon_minutes',
            field=models.PositiveSmallIntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='horizon_minutes',
            field=models.PositiveSmallIntegerField(default=240),
        ),
    ]
