# Generated by Django 5.2.16 on 2026-08-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_data', '0002_seed_official_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', '页面手动'), ('command', '命令行')], max_length=20)),
                ('mode', models.CharField(choices=[('incremental', '增量分析'), ('retry_failed', '重试失败'), ('smoke', '单条冒烟')], max_length=20)),
                ('analysis_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=160)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=20)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('rule_processed_count', models.PositiveIntegerField(default=0)),
                ('ai_processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('api_request_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['analysis_version', '-started_at'], name='news_an_run_ver_start_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('analysis_version',), name='news_analysis_one_running_ver')],
            },
        ),
        migrations.CreateModel(
            name='NewsAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('observation_result', models.CharField(blank=True, choices=[('noteworthy', '值得关注'), ('routine', '常规信息'), ('noise', '明显噪声'), ('insufficient', '信息不足')], max_length=20)),
                ('event_type', models.CharField(blank=True, choices=[('protocol_upgrade', '协议升级'), ('security_incident', '安全事件'), ('regulation_policy', '监管政策'), ('institutional_adoption', '机构采用'), ('ecosystem_development', '生态发展'), ('listing_delisting', '上币或下币'), ('trading_rule_change', '交易规则变化'), ('platform_operation', '平台运营'), ('market_activity', '市场活动'), ('marketing_activity', '营销活动'), ('research_report', '研究报告'), ('other', '其他'), ('unclear', '无法判断')], max_length=40)),
                ('impact_scope', models.CharField(blank=True, choices=[('ethereum', '以太坊'), ('ethereum_ecosystem', '以太坊生态'), ('crypto_market', '加密市场'), ('exchange', '交易所'), ('other_asset', '其他资产'), ('unclear', '无法判断')], max_length=40)),
                ('importance', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=20)),
                ('rationale', models.CharField(blank=True, max_length=500)),
                ('confidence', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=20)),
                ('method', models.CharField(blank=True, choices=[('rule', '固定规则'), ('ai', 'AI')], max_length=20)),
                ('matched_rule_id', models.CharField(blank=True, max_length=100)),
                ('actual_model_name', models.CharField(blank=True, max_length=160)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('analyzed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='news_data.newsrawrecord')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='news_analysis.newsanalysisrun')),
            ],
            options={
                'ordering': ['-analyzed_at', '-id'],
                'indexes': [models.Index(fields=['analysis_version', 'status'], name='news_an_res_ver_stat_idx'), models.Index(fields=['analysis_version', 'observation_result'], name='news_an_res_ver_obs_idx')],
                'constraints': [models.UniqueConstraint(fields=('news_record', 'analysis_version'), name='news_analysis_record_ver_unique')],
            },
        ),
    ]
