# Generated by Django 5.2.16 on 2026-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanalysisrun',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsanalysisrun',
            name='trigger',
            field=models.CharField(choices=[('manual', '页面手动'), ('scheduled', '定时工作流'), ('command', '命令行')], max_length=20),
        ),
    ]
