# Generated by Django 5.2.16 on 2026-08-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0004_add_rss_summary_stage'),
        ('news_data', '0008_seed_circle_pressroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveFactExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', '页面手动'), ('command', '命令行')], max_length=20)),
                ('mode', models.CharField(choices=[('incremental', '增量提取'), ('retry_failed', '重试失败')], max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('not_run', '未执行')], default='running', max_length=20)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('prompt_version', models.CharField(max_length=80)),
                ('generation_parameters', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('validation_passed_count', models.PositiveIntegerField(default=0)),
                ('validation_warning_count', models.PositiveIntegerField(default=0)),
                ('validation_error_count', models.PositiveIntegerField(default=0)),
                ('facts_count', models.PositiveIntegerField(default=0)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['prompt_version', '-started_at'], name='obj_fact_run_prompt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('prompt_version',), name='objective_fact_one_running_prompt')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveFactExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_status', models.CharField(choices=[('pending', '提取中'), ('success', '提取成功'), ('failed', '提取失败')], default='pending', max_length=20)),
                ('validation_status', models.CharField(choices=[('passed', '校验通过'), ('warning', '校验警告'), ('error', '校验错误')], default='error', max_length=20)),
                ('ai_call_succeeded', models.BooleanField(default=False)),
                ('json_parse_succeeded', models.BooleanField(default=False)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('prompt_version', models.CharField(max_length=80)),
                ('generation_parameters', models.JSONField(default=dict)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('has_stored_body', models.BooleanField(default=False)),
                ('stored_body_included', models.BooleanField(default=False)),
                ('input_scope_note', models.CharField(blank=True, max_length=300)),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('raw_model_output', models.TextField(blank=True)),
                ('parsed_result', models.JSONField(blank=True, null=True)),
                ('json_parse_error', models.TextField(blank=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('validation_warnings', models.JSONField(default=list)),
                ('evidence_matches', models.JSONField(default=list)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('objective_summary', models.TextField(blank=True)),
                ('event_status', models.CharField(blank=True, max_length=40)),
                ('information_completeness', models.CharField(blank=True, max_length=20)),
                ('facts_count', models.PositiveIntegerField(default=0)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_fact_results', to='news_data.newsrawrecord')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='news_analysis.objectivefactextractionrun')),
            ],
            options={
                'ordering': ['-extracted_at', '-id'],
                'indexes': [models.Index(fields=['news_record', 'prompt_version', '-id'], name='obj_fact_news_prompt_idx'), models.Index(fields=['prompt_version', 'extraction_status'], name='obj_fact_prompt_extract_idx'), models.Index(fields=['prompt_version', 'validation_status'], name='obj_fact_prompt_valid_idx'), models.Index(fields=['event_status', 'information_completeness'], name='obj_fact_event_info_idx'), models.Index(fields=['facts_count'], name='obj_fact_count_idx'), models.Index(fields=['has_stored_body'], name='obj_fact_body_idx')],
            },
        ),
    ]
