# Generated by Django 5.2.16 on 2026-08-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0005_objectivefactextractionrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivefactextractionresult',
            name='event_status',
            field=models.CharField(blank=True, choices=[('occurred', 'occurred'), ('approved', 'approved'), ('announced', 'announced'), ('proposed', 'proposed'), ('planned', 'planned'), ('ongoing', 'ongoing'), ('under_investigation', 'under_investigation'), ('unconfirmed', 'unconfirmed'), ('unknown', 'unknown')], max_length=40),
        ),
    ]
