# Generated by Django 5.2.16 on 2026-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0006_alter_objectivefactextractionresult_event_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectivefactextractionrun',
            name='objective_fact_one_running_prompt',
        ),
        migrations.AddField(
            model_name='objectivefactextractionresult',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionresult',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionresult',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionresult',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='concurrency_slot',
            field=models.CharField(default='objective_fact', max_length=40),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='processed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objectivefactextractionrun',
            name='triggered_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='objectivefactextractionrun',
            name='mode',
            field=models.CharField(choices=[('incremental', '增量提取'), ('retry_failed', '重试失败'), ('single', '单条提取'), ('retry_single', '单条重试'), ('reextract', '重新提取')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='objectivefactextractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('concurrency_slot',), name='objective_fact_one_running_global'),
        ),
    ]
