# Generated by Django 5.2.16 on 2026-08-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0007_remove_objectivefactextractionrun_objective_fact_one_running_prompt_and_more'),
        ('news_data', '0008_seed_circle_pressroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMergeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('succeeded_with_warnings', '成功（有警告）'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=30)),
                ('trigger', models.CharField(choices=[('manual', '页面手动'), ('scheduled', '定时工作流'), ('retry_failed', '重试失败项'), ('full_rebuild', '完整重建')], max_length=20)),
                ('request_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('pending', '等待开始'), ('scanning', '扫描输入'), ('candidates', '生成候选'), ('hard_rules', '执行硬规则'), ('ai_decisions', 'AI 判断'), ('grouping', '事件归组'), ('validating', '一致性校验'), ('activating', '切换有效快照'), ('completed', '完成')], default='pending', max_length=30)),
                ('total_progress', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('candidate_pair_count', models.PositiveIntegerField(default=0)),
                ('hard_rejected_count', models.PositiveIntegerField(default=0)),
                ('ai_decision_count', models.PositiveIntegerField(default=0)),
                ('ai_failure_count', models.PositiveIntegerField(default=0)),
                ('auto_grouped_event_count', models.PositiveIntegerField(default=0)),
                ('singleton_event_count', models.PositiveIntegerField(default=0)),
                ('uncertain_event_count', models.PositiveIntegerField(default=0)),
                ('final_event_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('algorithm_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('is_current_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retry_runs', to='news_analysis.eventmergerun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_title', models.TextField()),
                ('status', models.CharField(choices=[('provisional', '暂定'), ('uncertain', '不确定'), ('conflicted', '存在冲突')], default='provisional', max_length=20)),
                ('grouping_method', models.CharField(choices=[('singleton', '单成员'), ('auto_grouped', '自动归组')], max_length=20)),
                ('actors_snapshot', models.JSONField(default=list)),
                ('action_snapshot', models.TextField(blank=True)),
                ('object_snapshot', models.JSONField(default=list)),
                ('event_status_snapshot', models.CharField(blank=True, max_length=40)),
                ('objective_summary', models.TextField(blank=True)),
                ('event_time_text', models.CharField(blank=True, max_length=80)),
                ('earliest_publication_at', models.DateTimeField()),
                ('latest_publication_at', models.DateTimeField()),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('grouping_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='news_analysis.eventmergerun')),
            ],
            options={
                'ordering': ['-latest_publication_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPairDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('same_event', '同一事件'), ('not_same_event', '不同事件'), ('uncertain', '不确定'), ('hard_rejected', '硬规则拒绝'), ('processing_failed', '处理失败')], max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('same_event_basis', models.JSONField(default=list)),
                ('differences', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('canonical_title', models.TextField(blank=True)),
                ('has_fact_conflict', models.BooleanField(default=False)),
                ('algorithm_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('structured_response', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('succeeded', '已完成'), ('failed', '失败')], max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('safe_error_summary', models.CharField(blank=True, max_length=500)),
                ('is_retryable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_pair_decisions_left', to='news_analysis.objectivefactextractionresult')),
                ('right_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_pair_decisions_right', to='news_analysis.objectivefactextractionresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_decisions', to='news_analysis.eventmergerun')),
            ],
            options={
                'ordering': ['left_result_id', 'right_result_id'],
            },
        ),
        migrations.AddField(
            model_name='eventmergerun',
            name='retry_pair_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='single_retry_runs', to='news_analysis.eventpairdecision'),
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('primary', '主要成员'), ('corroborating', '补充成员')], max_length=20)),
                ('join_method', models.CharField(choices=[('singleton', '单成员创建'), ('auto_match', '高置信自动匹配')], max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='news_analysis.canonicalevent')),
                ('extraction_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_memberships', to='news_analysis.objectivefactextractionresult')),
                ('news_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_memberships', to='news_data.newsrawrecord')),
            ],
            options={
                'ordering': ['event_id', 'news_record__published_at', 'extraction_result_id'],
                'indexes': [models.Index(fields=['extraction_result'], name='event_member_result_idx'), models.Index(fields=['news_record'], name='event_member_news_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'extraction_result'), name='event_member_unique_result'), models.UniqueConstraint(fields=('event', 'news_record'), name='event_member_unique_news')],
            },
        ),
        migrations.AddIndex(
            model_name='canonicalevent',
            index=models.Index(fields=['run', 'status'], name='canon_event_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalevent',
            index=models.Index(fields=['run', 'grouping_method'], name='canon_event_run_group_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpairdecision',
            index=models.Index(fields=['run', 'relation'], name='event_pair_run_relation_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpairdecision',
            index=models.Index(fields=['run', 'processing_status'], name='event_pair_run_process_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventpairdecision',
            constraint=models.UniqueConstraint(fields=('run', 'left_result', 'right_result'), name='event_pair_unique_per_run'),
        ),
        migrations.AddConstraint(
            model_name='eventpairdecision',
            constraint=models.CheckConstraint(condition=models.Q(('left_result_id__lt', models.F('right_result_id'))), name='event_pair_canonical_order'),
        ),
        migrations.AddIndex(
            model_name='eventmergerun',
            index=models.Index(fields=['-started_at'], name='event_merge_started_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmergerun',
            index=models.Index(fields=['algorithm_version', 'prompt_version'], name='event_merge_versions_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmergerun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='event_merge_one_running_global'),
        ),
        migrations.AddConstraint(
            model_name='eventmergerun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_snapshot', True)), fields=('is_current_snapshot',), name='event_merge_one_current_snapshot'),
        ),
    ]
