# Generated by Django 5.2.16 on 2026-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('kline', 'K线')], default='kline', max_length=20)),
                ('exchange', models.CharField(choices=[('binance', 'Binance')], max_length=20)),
                ('market_type', models.CharField(choices=[('usd_m_futures', 'USD-M Futures')], max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(choices=[('1d', '1d'), ('1h', '1h')], max_length=5)),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('trigger', models.CharField(choices=[('manual', '手工')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='run_started_desc_idx'), models.Index(fields=['symbol', 'interval', '-started_at'], name='run_sym_int_started_idx')],
            },
        ),
    ]
