# Generated by Django 5.2.16 on 2026-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collectionrun_scheduled_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrun',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='data_type',
            field=models.CharField(choices=[('kline', 'K线'), ('open_interest', 'OI'), ('funding', 'Funding')], default='kline', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='interval',
            field=models.CharField(choices=[('1d', '1d'), ('1h', '1h'), ('actual', '实际结算')], max_length=10),
        ),
    ]
