# Generated by Django 5.2.16 on 2026-07-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collectionrun_failed_count_and_more'),
        ('news_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrun',
            name='news_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_runs', to='news_data.newssource'),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='data_type',
            field=models.CharField(choices=[('kline', 'K线'), ('open_interest', 'OI'), ('funding', 'Funding'), ('news', '新闻')], default='kline', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='exchange',
            field=models.CharField(blank=True, choices=[('binance', 'Binance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='interval',
            field=models.CharField(blank=True, choices=[('1d', '1d'), ('1h', '1h'), ('actual', '实际结算')], max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='market_type',
            field=models.CharField(blank=True, choices=[('usd_m_futures', 'USD-M Futures')], max_length=30),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
