# Generated by Django 5.2.16 on 2026-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_collectionrun_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrun',
            name='data_type',
            field=models.CharField(choices=[('kline', 'K线'), ('open_interest', 'OI'), ('funding', 'Funding'), ('deribit_dvol', 'Deribit DVOL'), ('deribit_option_instrument', 'Deribit期权合约'), ('deribit_option_snapshot', 'Deribit期权快照'), ('news', '新闻')], default='kline', max_length=30),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='exchange',
            field=models.CharField(blank=True, choices=[('binance', 'Binance'), ('deribit', 'Deribit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='market_type',
            field=models.CharField(blank=True, choices=[('usd_m_futures', 'USD-M Futures'), ('options', 'Options')], max_length=30),
        ),
    ]
