# Generated by Django 5.2.16 on 2026-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_collectionrun_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrun',
            name='data_type',
            field=models.CharField(choices=[('kline', 'K线'), ('open_interest', 'OI'), ('funding', 'Funding'), ('deribit_dvol', 'Deribit DVOL'), ('deribit_option_instrument', 'Deribit期权合约'), ('deribit_option_snapshot', 'Deribit期权快照'), ('news', '新闻'), ('stablecoin_supply', '稳定币供应'), ('eth_etf_flow', 'ETH ETF 资金流'), ('eth_address_balance', 'Ethereum 地址余额')], default='kline', max_length=30),
        ),
    ]
