# Generated by Django 5.2.16 on 2026-07-31 12:48

import apps.inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlineInspectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance')], max_length=20)),
                ('market_type', models.CharField(choices=[('usd_m_futures', 'USD-M Futures')], max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(choices=[('1d', '1d'), ('1h', '1h')], max_length=5)),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('trigger', models.CharField(choices=[('manual', '手工')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', '待判定'), ('passed', '通过'), ('issues', '发现问题')], default='pending', max_length=20)),
                ('expected_count', models.PositiveIntegerField(default=0)),
                ('actual_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('misaligned_count', models.PositiveIntegerField(default=0)),
                ('invalid_ohlc_count', models.PositiveIntegerField(default=0)),
                ('invalid_numeric_count', models.PositiveIntegerField(default=0)),
                ('invalid_close_time_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=apps.inspection.models.empty_inspection_details)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='inspect_started_desc_idx'), models.Index(fields=['symbol', 'interval', '-started_at'], name='inspect_sym_int_start_idx')],
            },
        ),
    ]
