# Generated by Django 5.2.16 on 2026-07-31 18:31

import apps.inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_derivativesinspectionrun_and_collection_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInspectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('trigger', models.CharField(choices=[('scheduled', '定时'), ('manual', '手工')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '完成'), ('failed', '检查执行失败')], default='running', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', '待判定'), ('passed', '通过'), ('warning', '警告'), ('failed', '失败')], default='pending', max_length=20)),
                ('coverage_complete', models.BooleanField(default=False)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('parsed_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('dimensions', models.JSONField(default=apps.inspection.models.empty_news_dimensions)),
                ('reasons', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
