# Generated by Django 5.2.16 on 2026-07-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collectionrun_news_source_and_more'),
        ('inspection', '0004_newsinspectionrun'),
        ('news_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinspectionrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_runs', to='news_data.newssource'),
        ),
        migrations.AddField(
            model_name='newsinspectionrun',
            name='source_collection_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_inspections', to='collection.collectionrun'),
        ),
        migrations.AddIndex(
            model_name='newsinspectionrun',
            index=models.Index(fields=['-started_at'], name='news_insp_started_idx'),
        ),
        migrations.AddIndex(
            model_name='newsinspectionrun',
            index=models.Index(fields=['source', '-started_at'], name='news_insp_src_start_idx'),
        ),
    ]
