# Generated by Django 5.2.16 on 2026-07-31 16:13

import apps.derivatives_evidence.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativesEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', '完整'), ('partial', '部分可用'), ('unavailable', '来源不可用'), ('failed', '计算失败')], max_length=20)),
                ('rule_version', models.CharField(default='derivatives-evidence-v1', editable=False, max_length=40)),
                ('calculated_at', models.DateTimeField()),
                ('data_range_start', models.DateTimeField()),
                ('data_range_end', models.DateTimeField()),
                ('coverage_snapshot', models.JSONField(default=apps.derivatives_evidence.models.empty_dict)),
                ('calculation_snapshot', models.JSONField(default=apps.derivatives_evidence.models.empty_dict)),
                ('rule_snapshot', models.JSONField(default=apps.derivatives_evidence.models.empty_dict)),
                ('source_snapshot', models.JSONField(default=apps.derivatives_evidence.models.empty_dict)),
                ('status_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives_evidence', to='research_cases.researchcase')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
